config/routes.rb
Rails.application.routes.draw do
  root 'zoos#index'

  resources :zoos do
    resources :animals
  end

  resources :animals do
    resources :comments
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :zoo
  has_many :comments, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :animal
end

app/models/zoo.rb
class Zoo < ApplicationRecord
  has_many :animals, dependent: :destroy
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_zoo
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  def index
    @animals = @zoo.animals
  end

  def show
  end

  def new
    @animal = @zoo.animals.new
  end

  def edit
  end

  def create
    @animal = @zoo.animals.new(animal_params)

    if @animal.save
      redirect_to [@zoo, @animal]
    else
      render :new
    end
  end

  def update
    if @animal.update(animal_params)
      redirect_to [@zoo, @animal]
    else
      render :edit
    end
  end

  def destroy
    @animal.destroy
    redirect_to zoo_animals_path
  end

  private
    def set_zoo
      @zoo = Zoo.find(params[:zoo_id])
    end

    def set_animal
      @animal = Animal.find(params[:id])
    end

    def animal_params
      params.require(:animal).permit(:name, :species, :age)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_animal

  def new
    @comment = Comment.new
  end

  def create
    @comment = @animal.comments.new(comment_params)

    if @comment.save
      redirect_to zoo_animal_path(@animal.zoo_id, @animal)
    else
      render :new
    end
  end

  private
    def set_animal
      @animal = Animal.find(params[:animal_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end
end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
  before_action :set_zoo, only: [:show, :update, :edit, :destroy]
  def index
    @zoos = Zoo.all
  end

  def show
  end

  def new
    @zoo = Zoo.new
  end

  def create
    @zoo = Zoo.new(zoo_params)

    if @zoo.save
      redirect_to zoos_path
    else
      reder :new
    end
  end

  def edit
  end

  def update
    if @zoo.update(zoo_params)
      redirect_to @zoo
    else
      render :edit
    end
  end

  def destroy
    @zoo.destroy
    redirect_to zoos_path
  end

  private

  def set_zoo
    @zoo = Zoo.find(params[:id])
  end

  def zoo_params
    params.require(:zoo).permit(:name)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/zoos_helper.rb
module ZoosHelper
end

app/views/animals/_form.html.erb
<h1><%= @animal.id ? 'Edit Animal' : 'Create Animal' %></h1>
<hr />
<%= form_with(model: [@zoo, @animal], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :species %>
  <%= f.text_field :species, required: true %>
  <br />
  <%= f.label :age %>
  <%= f.text_field :age, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render "form", zoo: @zoo, animal: @animal %>

<%= link_to "Back", zoo_animals_path(@zoo) %>

app/views/animals/index.html.erb
<h1>Click an Animal To View It</h1>
<%= link_to 'Add Animal', new_zoo_animal_path(@zoo) %>
<ul>
  <% @animals.each do |animal| %>
    <li><%= link_to animal.name, [@zoo, animal] %></li>
  <% end %>
</ul>
<%= link_to 'Back to Zoo', @zoo %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render "form", zoo: @zoo, animal: @animal %>

<%= link_to "Back", zoo_animals_path(@zoo) %>

app/views/animals/show.html.erb
<h1><%= @zoo.name %></h1>
<h4>Name: <%= @animal.name %></h4>
<h4>Species: <%= @animal.species %></h4>
<h4>Age: <%= @animal.age %></h4>
<br />
<h2>Comments</h2>
<% @animal.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %>
<br />
<%= link_to 'Add Comment', new_animal_comment_path(@animal), class: "ui button blue" %>
<br />
<br />
<%= link_to 'Edit Animal', edit_zoo_animal_path([@zoo, @animal]) %> |
<%= link_to 'Delete Animal', [@zoo, @animal], method: :delete %> |
<%= link_to 'Back To Animals', zoo_animals_path(@zoo) %>

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
<hr/>

app/views/comments/new.html.erb
<h1>Add A comment</h1>
<%= form_with(model: [@animal, @comment], local: true, class: "ui form") do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsZpp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/zoos/_form.html.erb
<%= form_with(model: zoo, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
<% end %>

app/views/zoos/edit.html.erb
<h1>Edit Zoo</h1>

<%= render "form", zoo: @zoo %>

<%= link_to "Show", zoo_path(@zoo) %> |
<%= link_to "Back", zoos_path %>

app/views/zoos/index.html.erb
<h1 class="ui header">All Zoos</h1>
<% @zoos.each do |zoo| %>
  <h1><%= zoo.name %></h1>
  <%= link_to "Show", zoo_path(zoo) %>
  <%= link_to "Edit", edit_zoo_path(zoo) %>
  <%= link_to "Destroy", zoo_path(zoo), method: :delete %>
<% end %>
<br />
<%= link_to "New Zoo", new_zoo_path %>

app/views/zoos/new.html.erb
<h1>New Zoo</h1>

<%= render "form", zoo: @zoo %>

<%= link_to "Back", zoos_path %>

app/views/zoos/show.html.erb
<div class="ui card">
  <div class="content">
    <p class="header">
      <%= @zoo.name %> <%= @zoo.name %>
    </p>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_zoo_path(@zoo) %> |
    <%= link_to 'View Animal', zoo_animals_path(@zoo) %> |
    <%= link_to 'Back', zoos_path %>
  </div>
</div>